name: Fly Deploy Prod
on:
  push:
    branches:
      - main
      - staging
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: run_flyctl
        run: |
          echo "github.ref is: ${{github.ref}}"
          if [[ "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "deploying to PROD"
            flyctl deploy --remote-only -a myapp-fly
          fi
          if [[ "${{github.ref}}" == "refs/heads/staging" ]]; then
            echo "deploying to DEV"
            flyctl deploy --remote-only -a myapp-fly-dev
          fi
